server:
  port: 8082
  servlet:
    context-path: /api

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gestioncommercial
    username: root
    password:

logging:
  level:
    org.springframework.web:
      ma.project: DEBUG
      org.hibernate: ERROR

